### PR TITLE
[BugFix] Replacing next and previous page query params to avoid repeated page params

### LINKED ISSUE #42: Wrong Previous and Next Pages calculated when page param sent
## Summary

When the pagination is made with a page param as a query param, it doesn't remove it from the url, but just adds the next or previous page, which could result in a wrong page url, for example: `next_page_url: 'http://apiurl:3000/endpoint?limit=1&page=1?page=2'`.

It should remove the existent page query params and just concat the desired one.

### PR DESCRIPTION
**Pull request by juanpablo-rojas**
## Summary
* Now the `page` query param is being replaced properly, checking if the incoming url had such param or not, to decide where to put this param for `next_page_link` and `previous_page_link` pagination params, and therefore, avoid repeated page params for these links or wrong page links.
* `next_page_url` and `previous_page_url` pag params names were changed to `next_page_link` and `previous_page_link` according to the Wolox Api Restful Guidelines
* A new test case for query params in the url was added

This is a solution to this issue: https://github.com/Wolox/pagination-node/issues/42

### CODE REVIEW

File: lib/pagination/adapter.js [hunk 1]
```diff
@@ -19,10 +19,21 @@ const totalPages = adapterParams => Math.ceil(totalCount(adapterParams) / adapte
...
+
+const pageUrl = (adapterParams, pageParam) => {
+  if (!pageParam) return null;
+
+  const { host } = adapterParams.request.headers;
+  const { url } = adapterParams.request;
+  if (!adapterParams.request.url.includes('?')) return `http://${host}${url}?page=${pageParam}`;
+
+  const newPageUrl = trimPageUrl(url, pageParam);
+  return `http://${host}${newPageUrl}`;
```
Comment (picollomartin) [inline lib/pagination/adapter.js:35]: You assume that the protocol is always HTTP here, could be HTTPS too. Also if you have the entire request you could check in the property request.query if the param page is present or not without parsing the entire URL string (and simplify the logic related with that)

**Review by picollomartin — CHANGES_REQUESTED** [review]

File: lib/pagination/adapter.js [hunk 2]
```diff
@@ -19,10 +19,21 @@ const totalPages = adapterParams => Math.ceil(totalCount(adapterParams) / adapte
 const nextPage = adapterParams =>
   adapterParams.page >= totalPages(adapterParams) ? null : adapterParams.page + 1;
 
-const pageUrl = (adapterParams, pageParam) =>
-  pageParam
-    ? `http://${adapterParams.request.headers.host}${adapterParams.request.url}?page=${pageParam}`
-    : null;
+const trimPageUrl = (originalUrl, newPageNum) => {
+  const newPageUrl = originalUrl.replace(/page=./, `page=${newPageNum}`);
```
Comment (Dinuuu) [inline lib/pagination/adapter.js:23]: Is this taking into account that the page might be a 2 or more digits number ? Because I think that `.` will just get 1 digit and if you are in page `10` for example you will only replace `page=1`

File: lib/pagination/adapter.js [hunk 3]
```diff
@@ -32,8 +43,8 @@ const contentPagination = adapterParams => ({
   previous_page: previousPage(adapterParams),
   current_page: adapterParams.page,
   next_page: nextPage(adapterParams),
-  previous_page_url: pageUrl(adapterParams, previousPage(adapterParams)),
-  next_page_url: pageUrl(adapterParams, nextPage(adapterParams))
+  previous_page_link: pageUrl(adapterParams, previousPage(adapterParams)),
```
Comment (Dinuuu) [inline lib/pagination/adapter.js:46]: is there a way we are changing the word previous_page_url for previous_page_link ? This is a breaking change with previous versions

**Review by Dinuuu — CHANGES_REQUESTED** [review]

File: lib/pagination/adapter.js (hunk 3 above)
Comment (Dinuuu) [reply lib/pagination/adapter.js:46]: I read that this change was due to standards/convention. Is there a way to let the mantainers know that they should bump the mayor version number ?

Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:46]: I guess not. I am the only maintainer right now as far as I know, and as this package is still gaining strength maybe it lack of many things. What do you suggest to do to bump versions properly?

File: lib/pagination/adapter.js (hunk 2 above)
Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:23]: You're totally right! I missed that posibility. Will cover that in the next commit

File: lib/pagination/adapter.js (hunk 1 above)
Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:35]: I don't have that `query` property you mention, the object that I get here is an `IncomingMessage` and it doesn't have its query params as simple as that, I would wish it was that simple, but that's why I'm parsing everything in this "manual" way. I am aware of that issue of `http` protocol, but while I think of a solution (IncomingMessage objects doesn't have a protocol property, or the entire url, they just bring the host, the method, the url after the `/` part, and nothing more) to convert better the url, I had to put this manually for now (at least to present a valid url, otherwise would be worst).

File: lib/pagination/adapter.js (hunk 3 above)
Comment (Dinuuu) [reply lib/pagination/adapter.js:46]: That depends of how you manage the versioning. I am guessing you would like to use something like https://semver.org/ .In that case the change you are introducing is a breaking change because if someone was using the `previous_page_url` or `next_page_url` attributes they will no longer find it and the app is going to crash so you will need to bump you MAYOR versión. On the other hand if you decide to just push the fix and maintain the original attributes, I would bump the PATCH version.
Since MAYOR versions are not retrocompatible, most persons don't have automatic updates that can jump between mayor versions so they wont receive the fix.

Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:46]: Thanks for the explanation! I agree that major change would force a bump to major version. I think it's not a problem, since there is only an internal project using this package. But I will discuss if there's no problem in bumping a major version, or I just let the real fix to the bug for a minor version and let the changed params for another bump. Thanks again!

**Review by Dinuuu — DISMISSED** [review]
After you correct what @picollomartin pointed out, I am okey merging it

File: lib/pagination/adapter.js (hunk 1 above)
Comment (picollomartin) [reply lib/pagination/adapter.js:35]: My mistake, I was thinking that you have an actual express request here. If you only have a raw URL you can parse it like this:
```javascript
const rawUrl = "https://my-url.com?q=1";
const parsedUrl = new URL(rawUrl);
```
Parsed URL contains something like:
```
URL {
  href: 'https://my-url.com/?q=1',
  origin: 'https://my-url.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'my-url.com',
  hostname: 'my-url.com',
  port: '',
  pathname: '/',
  search: '?q=1',
  searchParams: URLSearchParams { 'q' => '1' },
  hash: ''
}
```

Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:35]: Exactly, I don't have an actual express request because that would depend on the client that installs the paginator. About what you suggest, I also tried a workaround with the URL object, but it doesn't help me at all, because the object that I get is something like this:
```
IncomingMessage {_readableState: ReadableState, readable: true, _events: {…}, _eventsCount: 1, _maxListeners: undefined, …}
aborted: false
client: Socket {connecting: false, _hadError: false, _parent: null, _host: null, _readableState: ReadableState, …}
complete: false
connection: Socket {connecting: false, _hadError: false, _parent: null, _host: null, _readableState: ReadableState, …}
headers: {host: "127.0.0.1:50575", accept-encoding: "gzip, deflate", user-agent: "node-superagent/3.8.3", connection: "close"}
httpVersion: "1.1"
httpVersionMajor: 1
httpVersionMinor: 1
method: "GET"
rawHeaders: (8) ["Host", "127.0.0.1:50575", "Accept-Encoding", "gzip, deflate", "User-Agent", "node-superagent/3.8.3", "Connection", "close"]
rawTrailers: []
readable: true
socket: Socket {connecting: false, _hadError: false, _parent: null, _host: null, _readableState: ReadableState, …}
statusCode: null
statusMessage: null
trailers: {}
upgrade: false
url: "/index"
```
As you can see, there is nothing with the "whole url" I just have the `/` part... (what comes after the host domain), so I have to manually concat everything. URL works if I had the whole url and wanted to get parts of it, but this is the opposite case, I have to form a whole url based on the parts. If I'm missing something from the URL object that would fit this problem, let me know, but as far as I tried, URL object didn't help me at all.

Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:35]: Maybe I can convert everything to URL, and then parse everything with that object, and then return it again... I didn't wanted that because at the end I would still need to convert manually the url so it's the same thing. But maybe the replace/regexp part becomes smaller... anyways I will give it another try to that URL object approach.

File: lib/pagination/adapter.js [hunk 4]
```diff
@@ -21,10 +21,13 @@ const totalPages = adapterParams => Math.ceil(totalCount(adapterParams) / adapte
...
   adapterParams.page >= totalPages(adapterParams) ? null : adapterParams.page + 1;
 
-const pageUrl = (adapterParams, pageParam) =>
-  pageParam
-    ? `http://${adapterParams.request.headers.host}${adapterParams.request.url}?page=${pageParam}`
-    : null;
+const pageUrl = (adapterParams, pageParam) => {
+  if (!pageParam) return null;
+
+  const urlObject = new URL(`http://${adapterParams.request.headers.host}${adapterParams.request.url}`);
```
Comment (picollomartin) [inline lib/pagination/adapter.js:27]: If we can't determine this, I see two options:
- Add a parameter with the base URL of the API and use that as a prefix
- (worst) assume https instead of http

Comment (juanpablo-rojas) [reply lib/pagination/adapter.js:27]: I like your idea of adding a parameter for the protocol or the URL. Anyway, could we cover that in this particular issue? https://github.com/Wolox/pagination-node/issues/45 . Later I can work on a PR covering specifically that situation. This PR is covering another issue with the concated pages.

**Review by picollomartin — APPROVED** [review]
